import { testArray } from './Array.uts'
import { testDate } from './Date.uts'
import { testString } from './String.uts'
import { testError } from './Error.uts'
import { testJSON } from './JSON.uts'
import { testNumber } from './Number.uts'
import { testMap } from './Map.uts'
import { testSet } from './Set.uts'
import { testOperators } from './Operators.uts'
import { testMath } from './Math.uts'
import { testRegExp } from './RegExp.uts'
// #ifdef APP-ANDROID
// import { testReactiveArray } from './reactiveArray.uts'
// import { testReactiveMap } from './ReactiveMap.uts'
// #endif
export { Result } from './tests.uts'

// Promise、Proxy、Reflect、Weakmap、WeakSet 不支持
export function runTests() : UTSJSONObject {
    const ArrayRes = testArray();
    const DateRes = testDate();
    const StringRes = testString();
    const ErrorRes = testError();
    const JsonRes = testJSON();
    const NumberRes = testNumber();
    const MapRes = testMap();
    const SetRes = testSet();
    const OperatorsRes = testOperators();
    const MathRes = testMath();
    const RegExpRes = testRegExp();
    // #ifdef APP-ANDROID
    // const ReactiveArrayRes = testReactiveArray();
    // const ReactiveMapRes = testReactiveMap();
    // #endif

    return {
        Array: ArrayRes,
        // #ifdef APP-ANDROID
        // ReactiveArray: ReactiveArrayRes,
        // #endif
        Date: DateRes,
        String: StringRes,
        Error: ErrorRes,
        Json: JsonRes,
        Number: NumberRes,
        Map: MapRes,
        // #ifdef APP-ANDROID
        // ReactiveMap: ReactiveMapRes,
        // #endif
        Set: SetRes,
        Operators: OperatorsRes,
        Math: MathRes,
        RegExp: RegExpRes,
    }
}